// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { join } from 'path';
import { defineConfig } from 'prisma/config';

const envFiles = [join(process.cwd(), '.env'), join(process.cwd(), 'backend', '.env')];
for (const envPath of envFiles) {
  dotenv.config({ path: envPath, override: false });
}

let migrationUrl = process.env['DIRECT_URL'] || process.env['DATABASE_URL'] || '';
// Le pooler Supabase sur le port 6543 (Transaction Mode) bloque les verrous pg_advisory_lock de Prisma Migrate.
// On bascule automatiquement sur le port 5432 (Session Mode) qui supporte nativement les migrations Prisma :
if (migrationUrl.includes(':6543')) {
  migrationUrl = migrationUrl.replace(':6543', ':5432');
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: migrationUrl,
    // @ts-ignore
    directUrl: migrationUrl,
  },
});
